name: Local deployment to Kind
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  deploy-windows:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3
      - name: Helm deployment
        env:
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
        run: |
          helm upgrade api spring-cubix --install -f api.yaml -n cubix
          helm upgrade db spring-cubix --install -f db.yaml -n cubix --set env[2].value="$env:POSTGRESQL_PASSWORD"
# Swap commenting if your self-hosted agent is on Linux or on MacOS
#  deploy-linux:
#    runs-on: [self-hosted, linux, macOS]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Helm deployment
#        env:
#          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
#        run: |
#          helm upgrade api spring-cubix --install -f api.yaml -n cubix
#          helm upgrade db spring-cubix --install -f db.yaml -n cubix --set env[2].value="$POSTGRESQL_PASSWORD"
